- name: Create Secutiry Group Ansible
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group Ansible
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Create EC2 Instance
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2

- name: Adding Ec2 instance to a temp inventory
  add_host: name={{ item.public_ip }} groups=ansible-new
  with_items: "{{ ec2.instances }}"

- name: Adding Ec2 instance to hosts
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[ec2-instances]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Lazy SSH
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: Adding Ec2 Instances Tags
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: Ansible Provisioning